# Generated by Django 4.1.4 on 2023-12-16 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='kind',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Вид'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='total_reviews',
            field=models.IntegerField(default=0, verbose_name='Кількість відгуків'),
        ),
        migrations.AddField(
            model_name='place',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='Загальна оцінка'),
        ),
    ]
