# Generated by Django 4.1.4 on 2023-12-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_place_kind_place_total_reviews_place_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='average_review_score',
            field=models.FloatField(default=0, verbose_name='Середня оцінка відгуків'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Довгота'),
        ),
    ]
