# Generated by Django 4.1.4 on 2023-12-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_image_place_image_alter_attendance_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/main/img/event/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/main/img/place/'),
        ),
    ]
