# Generated by Django 4.1.4 on 2023-12-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_event_image_alter_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='type', max_length=255, verbose_name='Тип'),
        ),
    ]
