# Generated by Django 4.1.4 on 2023-12-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_city_event_country_event_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/event/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/place/'),
        ),
    ]
