# Generated by Django 4.1.4 on 2023-12-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_event_image_alter_place_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.TextField(default=' ', verbose_name='Гості'),
        ),
    ]
