# Generated by Django 4.1.4 on 2023-12-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_review_event_alter_event_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default='Львів', max_length=255, verbose_name='Місто, населений пункт'),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(default='Україна', max_length=255, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(default='Львівська область', max_length=255, verbose_name='Регіон, область'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(default='Не вказано', max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(default='Львів', max_length=255, verbose_name='Місто, населений пункт'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(default='Україна', max_length=255, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.CharField(default='Львівська область', max_length=255, verbose_name='Регіон, область'),
        ),
    ]
