# Generated by Django 4.1.4 on 2023-12-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
